#!/usr/bin/env bash

usage-add() {
    cat << EOF
Usage: star add PATH [NAME]
       star a PATH [NAME]

Add a new star.

    PATH
        Relative path to the directory to star.
        e.g. "star add ." will star the current directory

    NAME
        The name of the new star if provided, otherwise it will use the name of the current directory.
        - Must be unique (among all stars)
        - Can contain slashes: "/"
        - Whitespaces will be replaced by a dash: "-"
        - Names with only numeric characters will by prefixed by "dir-"
EOF
}

usage-list() {
    cat << EOF
Usage: star list [OPTIONS]
       star L [OPTIONS]

List all stars, by default sorted according to last load (top ones are the last loaded stars).

Listing can be customized either by:
- editing the environment variables in the configuration file (see 'star config' for more information)
- using options supported by the 'star-list' helper script

Get the 'star-list' usage and options by running: 
 "\${_STAR_HOME}/libexec/star/star-list" --help
EOF
}

usage-load() {
    cat << EOF
Usage: star load [STAR]
       star l [STAR]

Navigate (cd) into the starred directory.

By default, giving no argument will list the stars, to provide a single command for listing and navigating.
This behavior can be disabled by setting the environment variable "__STAR_ENABLE_LOADLISTS" to "no".

    STAR
        Should be the name or index of a starred directory (one that is listed using "star list").
EOF
}

usage-rename() {
    cat << EOF
Usage: star rename <STAR> <NEW_STAR_NAME>

Rename an existing star.

    STAR
        Should be the name of a starred directory.

    NEW_STAR_NAME
        The new name of the star.
        - Must be unique (among all stars)
        - Can contain slashes /
EOF
}

usage-remove() {
    cat << EOF
Usage: star remove <STAR> [STAR]...
       star rm <STAR> [STAR]...

Remove one or more stars.

    STAR
        Should be the name of a starred directory.
EOF
}

usage-reset() {
    cat << EOF
Usage: star reset [-f|--force]

Remove all stars and the ".star" directory.

    --force, -f
        Force reset without prompting the user.
EOF
}

usage-config() {
    cat << EOF
Usage: star config

Open the star configuration file in a terminal text editor then apply the updated configuration.

Configuration file:
    The configuration file is located at \$_STAR_CONFIG_FILE, which is by default "\$_STAR_CONFIG_HOME/star_config.sh".
    Customizing \$_STAR_CONFIG_FILE will allow you to use any file for star configuration. Keep in mind that this file will get sourced after each "star config".

    Customizing \$_STAR_CONFIG_HOME will allow you to change the directory where the default configuration file is stored (star_config.sh).
    By default, this corresponds to:
        - "\$XDG_CONFIG_HOME/star" if XDG_CONFIG_HOME is defined
        - else "\$HOME/.config/star"

    If the configuration file does not exist, star will suggest a command to create one from a provided template.

    Template location:
        \$_STAR_HOME/share/star/config/star_config.sh.template

Editor:
    - use the one defined in the environment variable \$EDITOR
    - else use "nano" if available
    - else use "vi" if available
EOF
}

# the following function could be another implementation of "star config",
# where it does not open the file in an editor, but:
# - without option displays the current configuration
# - else edits the configuration file according to the provided option

# usage-config() {
#     cat << EOF
# Usage: star config [OPTION]

# Display or edit the "star" configuration.

#     (d) default config

#     OPTION
#         list.sort
#             name (d)    Sort according to star's name.
#             loaded      Sort according to star's most recent load (cd)
#         list.order
#             desc (d)    Descending order
#             asc         Ascending order
#         list.index
#             none        No index
#             desc        Descending numeric index
#             asc (d)     Ascending numeric index

#         variables       Whether to enable (yes) or disable (no) the environment variables
#             yes (d)
#             no
# EOF
# }

usage-default() {
    cat << EOF
Usage: star [MODE]
       star [OPTION]

Dynamically bookmark and cd into directories.
Bookmarks are called "stars".

    MODE (related to stars management)
        add     Add a new star
        list    List all stars
        load    cd into a starred directory
        rename  Change the name of a star
        remove  Remove a star
        reset   Delete all stars

    MODE (miscellaneous)
        config  Edit configuration file and apply changes
        help    Show this help message

    Get more information for each mode using:
        star MODE --help
        star help MODE

    OPTION
        -h, --help          Show this help message
        -v, --version       Show star version
        -I, --info          Show more information about the star installation
EOF
}

mode=default

while [[ $# -gt 0 ]]; do
    opt="$1";
    shift;
    # we could remove double quotes
    case "$opt" in
        "-m"|"--mode="* )
            if [[ ${#opt} -eq 2 ]]; then
                mode="$1"
                shift
            else
                mode="${opt#*=}"
            fi
            modes_list=(default add list load rename remove reset config)

            if [[ ! "${modes_list[*]}" =~ (^|[[:space:]])"$mode"($|[[:space:]]) ]]; then
                echo >&2 "Invalid mode: $mode"
                exit 2
            fi
            ;;
        -*)
            echo >&2 "Invalid option: $opt"
            exit 1
            ;;
        *)
            echo >&2 "Invalid argument: $opt"
            exit 1
            ;;
   esac
done

usage-$mode
