name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout to main branch
        uses: actions/checkout@v6
        with:
          ref: main
          fetch-depth: 0  # full history and tags

      - name: Create archive
        id: create-archive
        run: |
          LATEST_TAG="$(git describe --tags --abbrev=0)"

          if ! [[ "${LATEST_TAG}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Tag name is invalid: \"${LATEST_TAG}\""
            exit 1
          fi

          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

          LATEST_VERSION=${LATEST_TAG/v/}

          if [[ "$LATEST_VERSION" != "$(cat ./share/star/VERSION)" ]]; then
            echo "Latest version in file ./share/star/VERSION does not correspond to latest tag version."
            echo "./share/star/VERSION: \"$(cat ./share/star/VERSION)\""
            echo "LATEST_TAG: \"${LATEST_TAG}\""
            exit 1
          fi

          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

          ./configure --prefix=
          error_code=$?
          if [[ $error_code != 0 ]]; then
            echo "Configure failed with error code $error_code"
            exit $error_code
          fi

          ./install.sh --release
          error_code=$?
          if [[ $error_code != 0 ]]; then
            echo "Archive creation failed with error code $error_code"
            exit $error_code
          fi

          ARCHIVE_NAME="star-${LATEST_VERSION}.tar.gz"

          if [[ ! -e ${ARCHIVE_NAME} ]]; then
            echo "Archive does not exist: \"${ARCHIVE_NAME}\""
            exit 2
          fi

          echo "ARCHIVE_NAME=$ARCHIVE_NAME" >> $GITHUB_ENV

      - name: Create checksum
        id: create-checksum
        run: |
          CHECKSUM_NAME="checksum.sha512.txt"
          sha512sum "${ARCHIVE_NAME}" > "${CHECKSUM_NAME}"
          echo "CHECKSUM_NAME=$CHECKSUM_NAME" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: steps.create-archive.outcome == 'success'
        with:
          tag_name: $LATEST_TAG
          name: $LATEST_TAG
          files: |
            "$ARCHIVE_NAME"
            "$CHECKSUM_NAME"